#!/usr/bin/env bash

if ! command -v zsh &> /dev/null
then
	echo -e "in order for setup to continue, you must install zsh. Do it in another tab and press any key when done:"
	read confirm
fi

if ! [ -d ~/.oh-my-zsh ]
then
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
	A
fi


